"""Every Results statistic, in the order the section reads, in one report.

Runs the three section analyses and writes their output to
`results/_analysis_results.md` (or `results/_analysis_<sections>.md` for a
subset), as well as printing it.

  f1   f1_emergence.py         Spectral structure predicts law-specific emergence
  f2   f2_identifiability.py   Structural identifiability determines emergence
  f3   f3_integration.py       One linking fact unlocks many inferences

Each figure's report has a main part, for numbers the Results text may quote,
and a supplementary part for diagnostics, conditional quantities and
descriptions of sentences the text may drop.  Shared estimation and formatting
live in `common.py`, whose docstring states the conventions every number
follows.

  usage:  python run_all.py          all three
          python run_all.py f2 f3    a subset
"""

import sys
import time

import _boot  # noqa: F401
import _paths  # noqa: F401
from _paths import result

import f1_emergence
import f2_identifiability
import f3_integration
from common import emit

SECTIONS = {"f1": f1_emergence, "f2": f2_identifiability, "f3": f3_integration}


def main():
    which = sys.argv[1:] or list(SECTIONS)
    lines = ["# Results statistics", "",
             "Generated by `code/analysis/run_all.py` from the stored records. "
             "Nothing is trained.", ""]
    for key in which:
        t0 = time.time()
        part = SECTIONS[key].report()
        emit(part + ["(%s: %.0f s)" % (key, time.time() - t0), ""])
        lines += part
    name = ("_analysis_results.md" if which == list(SECTIONS)
            else "_analysis_%s.md" % "_".join(which))
    with open(result(name), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote %s" % result(name))


if __name__ == "__main__":
    main()
